# Generated by Django 4.2.16 on 2024-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num_of_items',
            field=models.IntegerField(default=0),
        ),
    ]
