# Generated by Django 4.2.16 on 2024-12-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_cart_num_of_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='num_of_items',
        ),
    ]
